[tool.poetry]
name = "data.all"
version = "2.6.1"
description = "data.all"
package-mode = false

[virtualenvs]
create = false  # Prevents venv creation
in-project = false  # Optional, but recommended when create = false

[tool.ruff]
line-length = 120
src = ["backend", "deploy"]
target-version = "py39"

[tool.ruff.lint]
exclude = [ "tests/**", "**/input_types.py", "**/mutations.py", "**/queries.py", "**/types.py", "**/api/__init__.py"]
#select = ["D", "E", "F", "I", "PL", "RUF100", "W", "FA", "UP", "PYI036"]
ignore=[
    "E501",
    "F841",
    "F403",
    "F401",
    "E712",
    "E203",
    "E741"
]


[tool.ruff.lint.pylint]
max-args = 25  # Maximum number of arguments for function / method.
max-bool-expr = 5  # Maximum number of boolean expressions in an if statement (see R0916).
max-branches = 15  # Maximum number of branch for function / method body.
max-locals = 30  # Maximum number of locals for function / method body.
max-public-methods = 20  # Maximum number of public methods for a class (see R0904).
max-returns = 6  # Maximum number of return / yield for function / method body.
max-statements = 50  # Maximum number of statements in function / method body.

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true
